import Link from "next/link"

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <div className="container mx-auto px-4 py-8 flex-1">
        <Link href="/" className="text-sm text-primary hover:underline mb-6 inline-block">
          ← Back to Home
        </Link>

        <h1 className="text-4xl font-bold text-foreground mb-8">Privacy Policy</h1>

        <div className="prose prose-slate max-w-none space-y-6 text-foreground">
          <section>
            <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
            <p className="text-muted-foreground leading-relaxed">
              This Privacy Policy explains how the AI Prompt Grader application collects, uses, and protects information
              during your use of our service. We are committed to maintaining the privacy and security of your
              information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Information We Collect</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">We collect the following information:</p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Prompt Submissions: The text prompts you submit for evaluation</li>
              <li>Evaluation Results: Scores and metrics generated by our AI evaluation system</li>
              <li>Timestamp: When submissions are made</li>
              <li>Feedback: Optional ratings and comments you provide about the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">How We Use Your Information</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">
              The information collected is used exclusively for:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Providing prompt evaluation and feedback</li>
              <li>Generating anonymous analytics for instructors</li>
              <li>Improving the educational experience</li>
              <li>Understanding service effectiveness</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Data Storage and Security</h2>
            <p className="text-muted-foreground leading-relaxed">
              Submission data is stored temporarily in server memory for analytics purposes. We do not collect any
              personally identifiable information such as names, email addresses, or IP addresses beyond what is
              necessary for service operation.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Third-Party Services</h2>
            <p className="text-muted-foreground leading-relaxed">
              We use OpenAI's API to provide AI-powered evaluation. Your prompts are sent to OpenAI for processing
              according to their privacy policy and data usage terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Your Rights</h2>
            <p className="text-muted-foreground leading-relaxed">
              You have the right to know what data we collect and how it's used. Since we don't collect personally
              identifiable information, there is no personal data to request or delete.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Changes to This Policy</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update this Privacy Policy from time to time. Any changes will be posted on this page with an
              updated revision date.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have questions about this Privacy Policy, please contact your workshop instructor.
            </p>
          </section>

          <p className="text-sm text-muted-foreground mt-8">Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  )
}
